version: "3.8"

services:
  server_fichame:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server_fichame
    # ports:
    #   - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb_fichame
    networks:
      - reverse_proxy_network

  client_fichame:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client_fichame
    depends_on:
      - server_fichame
    networks:
      - reverse_proxy_network

  mongodb_fichame:
    image: mongo:latest
    container_name: mongodb_fichame
    volumes:
      - fichame_data:/data/db
    networks:
      - reverse_proxy_network

volumes:
  fichame_data:

networks:
  reverse_proxy_network:
    external: true
